storage:
  levelDBPath: storage/db
  storageUrl: http://localhost:1112
network:
  nodeName: org1
  httpPort: 1113
#  TODO
  localAddr: 127.0.0.1
  grpcPort: :1114
  socketPath: ./sockets/socket.sock
logger:
  level: debug
#  编码格式: json,console
  encoding: console
#  是否向控制台写入
  writeConsole: true

  filename: ../logs/compute/compute.log
  maxsize: 10
  maxBackUps: 10
  maxAge: 10
  compress: true
