storage:
  mongoDBAddr: 172.0.0.1:3306
  mongoDBPort: 3345
network:
  httpAddr: 127.0.0.1
  httpPort: 1112
logger:
  level: debug
  // 编码格式: json,console
  encoding: console
  writeConsole: true

  filename: logs/compute/kamier.log
  maxsize: 10
  maxBackUps: 10
  maxAge: 10
  compress: true
