storage:
  mongoDBAddr: 127.0.0.1
#  mongoDBAddr: 192.168.43.128
  mongoDBPort: 27017
  dbName: storage
  delete: true
  username: xl
  password: 1112
network:
  httpAddr: 127.0.0.1
  httpPort: 1112
logger:
  level: debug
# 编码格式: json,console
  encoding: console
# 是否写入终端
  writeConsole: true

  filename: ../logs/storage/storage.log
  maxsize: 10
  maxBackUps: 10
  maxAge: 10
  compress: true
